# -*- coding: utf-8 -*-
"""study_log.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rlN-vKWC7_Jc1RQY2mLbXNb09d1r0NjZ
"""

import csv
from datetime import datetime

kamoku = input("勉強した科目は？：")
time = input("何分勉強しましたか？：")

filename = "study_log.csv"

with open(filename, mode="a", newline="", encoding="utf-8") as file:
    writer = csv.writer(file)
    writer.writerow([datetime.now().strftime("%Y-%m-%d %H:%M"), kamoku, time])

print(f"勉強記録を保存しました！（{filename}）")

